name: enquiry_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  get: ^4.7.2
  google_fonts: ^6.3.2
  pinput: ^5.0.0
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  flutter_local_notifications: ^22.0.0
  get_storage: ^2.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
