// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQ14JB3XCZQPJ2iGqLwTGWL7Kdulb5yw',
    appId: '1:62121426871:web:9c7a148ab606116d8ef232',
    messagingSenderId: '62121426871',
    projectId: 'bbsmit-notifications',
    authDomain: 'bbsmit-notifications.firebaseapp.com',
    storageBucket: 'bbsmit-notifications.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn16-q9p4ucsipzdhX74Uu-7bpYU0E1ck',
    appId: '1:62121426871:android:0ddd98cd1ebf50168ef232',
    messagingSenderId: '62121426871',
    projectId: 'bbsmit-notifications',
    storageBucket: 'bbsmit-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-aMaTUAXCaxZsQRM1j5dB2pdOJh_8k8A',
    appId: '1:62121426871:ios:93fac6f2849247f18ef232',
    messagingSenderId: '62121426871',
    projectId: 'bbsmit-notifications',
    storageBucket: 'bbsmit-notifications.firebasestorage.app',
    iosBundleId: 'com.ahit.enquiryHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-aMaTUAXCaxZsQRM1j5dB2pdOJh_8k8A',
    appId: '1:62121426871:ios:93fac6f2849247f18ef232',
    messagingSenderId: '62121426871',
    projectId: 'bbsmit-notifications',
    storageBucket: 'bbsmit-notifications.firebasestorage.app',
    iosBundleId: 'com.ahit.enquiryHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvQ14JB3XCZQPJ2iGqLwTGWL7Kdulb5yw',
    appId: '1:62121426871:web:864a547e86d709688ef232',
    messagingSenderId: '62121426871',
    projectId: 'bbsmit-notifications',
    authDomain: 'bbsmit-notifications.firebaseapp.com',
    storageBucket: 'bbsmit-notifications.firebasestorage.app',
  );
}
